In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
import pickle

df = pd.read_csv('../data/gaming_churn.csv')

# Create binary churn target
df['Churn'] = df['EngagementLevel'].apply(lambda x: 0 if x == 'High' else 1)

# Drop original target (we replaced it)
df.drop(columns=['EngagementLevel', 'PlayerID'], inplace=True, errors='ignore')

df.head()

,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,Churn
0,43,Male,Other,Strategy,16.271119,0,Medium,6,108,79,25,1
1,29,Female,USA,Strategy,5.525961,0,Medium,5,144,11,10,1
2,22,Female,USA,Sports,8.223755,0,Easy,16,142,35,41,0
3,35,Male,USA,Action,5.265351,1,Easy,9,85,57,47,1
4,33,Male,Europe,Action,15.531945,0,Medium,2,131,95,37,1

In [2]:
categorical_cols = df.select_dtypes(include='object').columns.tolist()
print("Categorical columns:", categorical_cols)

le = LabelEncoder()
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

df.head()

Categorical columns: ['Gender', 'Location', 'GameGenre', 'GameDifficulty']

,Age,Gender,Location,GameGenre,PlayTimeHours,InGamePurchases,GameDifficulty,SessionsPerWeek,AvgSessionDurationMinutes,PlayerLevel,AchievementsUnlocked,Churn
0,43,1,2,4,16.271119,0,2,6,108,79,25,1
1,29,0,3,4,5.525961,0,2,5,144,11,10,1
2,22,0,3,3,8.223755,0,0,16,142,35,41,0
3,35,1,3,0,5.265351,1,0,9,85,57,47,1
4,33,1,1,0,15.531945,0,2,2,131,95,37,1

In [3]:
X = df.drop(columns=['Churn'])
y = df['Churn']

print("Features shape:", X.shape)
print("Churn distribution:\n", y.value_counts())

Features shape: (40034, 11)
Churn distribution:
 Churn
1    29698
0    10336
Name: count, dtype: int64

In [4]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

# Save scaler for deployment later
with open('../models/scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

print("Scaling done. Saved scaler.pkl")

Scaling done. Saved scaler.pkl

In [5]:
X_scaled.to_csv('../data/X_processed.csv', index=False)
y.to_csv('../data/y_processed.csv', index=False)
print("Saved processed data.")

Saved processed data.